---
title: "Respiratory Disease Outbreaks in Toronto Pre, During, and Post Covid-19 Pandemic "
subtitle: How Coronavirus and Other Respiratory Diseases have responded to the covid-19 pandemic and Toronto pandemic policies
author: 
  - Evelyn Hughes
thanks: "Code and data are available at: [https://github.com/EveHughes/Donaldson-Paper)."
date: 05/12/2025
date-format: long


execute:
  echo: false

abstract: "Through the analysis of Outbreaks in Toronto Healthcare Institutions, this paper seeks to identify the trends in respiratory infections in Toronto during the implementation and later lifting of covid-19 preventatory policies, including general trends in number of outbreaks, and makeup of respiratory infections. Through data visualization, this analysis finds that while reported coronavirus outbreaks have lowered since pandemic times, “secondary” respiratory diseases such as Influenza (A & B), Parainfluenza, Respiratory Syncytial Virus (RSV), Metapneumovirus, and Rhinovirus that were at lower levels during the pandemic have begun to rise again. At the same time, covid becomes a lesser percentage of overall respiratory diseases. Given different respiratory diseases require different treatment, these findings are relevant for informing healthcare facilities to place a lesser emphasis on covid-19, etc."

format: 
  pdf: 
    fig-pos: "H"
number-sections: true
bibliography: references.bib
---

# Introduction

On January 25, 2020, the first case of COVID-19 was reported in Canada, in a healthcare facility in Toronto (Cheese 2025). Around two months later on March 17, Doug Ford declared a state of emergency for Ontario, and the closure of facilities such as schools. Additionally, mask mandates, social distancing guidelines, and vaccine cards were all put into place to mitigate the spread of the disease. Later around 2022, these restrictions began to lift. Schools went back in person, etc, etc, etc. (Compartin 2022). As the restrictions lift, it becomes important to characterize the effect they hold upon respiratory diseases both as a whole, and specific diseases.

Previously, in 2021, research was conducted to examine the effects of covid protocol on other respiratory diseases, finding evidence for a decrease in disease during covid protocol (Groves et al 2021). However, there is a lack of literature examining the effects of the lifting of protocol on these same diseases, and examining the general trends. This research aims to fill that gap, and identify how diseases have reacted to the lifting of covid protocol in relation to both their pre covid (2019), and during covid (2020-2022 ish) levels. Doing such can inform policy that encourages disease-specific preventative measures, and promotion of vaccines to prevent increased outbreaks.

This analysis first examines the trends in the overall number of outbreaks and respiratory outbreaks each year to better understand how the number of outbreaks has been varying over the years and identify general trends. Then, it looks at coronavirus, Influenza (A & B), Parainfluenza, Respiratory Syncytial Virus (RSV), Metapneumovirus, and Rhinovirus. Finally, it examines the trends in percentage of respiratory outbreaks with covid as an agent. Through the data visualization, it was found that while coronavirus outbreaks have been falling since their covid levels, other respiratory diseases have been seeing a subsequent increase in cases post pandemic. Additionally, the percentage of respiratory outbreaks with covid as an agent has been decreasing since the pandemic. So, while an emphasis on covid specific protocols is important, preventative measures for other respiratory diseases, such as RSV vaccines, that were overshadowed during the pandemic should be further encouraged (Public Health Agency of Canada 2024).

In the sections that follow are a description of the data, visualization of the data and discussion of the results.


# Data {#sec-data}

## Raw Data

Outbreaks in Toronto Healthcare Institutions data is provided by Toronto Public Health., and is obtained from the OpenData Toronto Portal. The dataset is updated weekly on Thursdays with data as of the Wednesday at 2pm.(https://open.toronto.ca/dataset/outbreaks-in-toronto-healthcare-institutions/ ). 

The dataset consists of data from years 2016-2025 inclusive, with each containing instances of outbreaks in toronto healthcare institutions. 

“Under the Ontario Health Protection and Promotion Act (HPPA), healthcare institutions (hospitals, long-term care homes and retirement homes) are required to monitor staff and patients/residents for signs and symptoms of gastroenteric (e.g., nausea, vomiting, diarrhea, fever) and respiratory (e.g., cough, runny nose, sore throat, fever) infections. Healthcare institutions must also actively look for, detect and report suspected and/or confirmed outbreaks to their local public health unit”

For every record there is an id number, institution name, institution address, outbreak setting (type of facility), type of outbreak, causative agent-1, causative agent-2, date outbreak began, date outbreak ended, and whether the outbreak is currently active. Below is a preview of this information:

The type of outbreak is listed as Respiratory, Enteric, or Other.
By the Ministry of Health, a respiratory outbreak is constituted by “Two cases of acute respiratory infections (ARI) within 48 hours with any common epidemiological link (e.g., unit, floor), at least one of which must be laboratory-confirmed; OR Three cases of ARI (laboratory confirmation not necessary) occurring within 48 hours with any common epidemiological link (e.g., unit, floor). https://www.toronto.ca/wp-content/uploads/2023/06/9942-Outbreak-Preparedness-ToolkitRespiratoryTableTopFacilitators.pdf

Healthcare facilities include ....

Causative Agent-1 is either a specific agent (ie: Coronavirus), or "Unable to identify".
Causative Agent-2 is either a specific agent, or "None".

Below is an example of the raw data from 2019:

```{python}
#| label: fig-polar
#| fig-cap: "A line plot on a polar axis"

import polars as pl
import matplotlib.pyplot as plt
pl.Config.set_tbl_hide_column_data_types(True)  
pl.Config(tbl_width_chars=1000)

raw_data = pl.read_csv("../data/01-raw_data/ob_report_2019.csv")
for key in raw_data.columns:
  if key not in ["_id", "Type of Outbreak", "Causative Agent-1", "Causative Agent-2"]:
    raw_data = raw_data.drop(key)
raw_data.head(5)

```

For this analysis, the variables of interest are the yearly number of outbreaks for Influenza (A & B), Parainfluenza, Respiratory Syncytial Virus (RSV), Metapneumovirus, and Rhinovirus. Over 2019-2024. 


## Analysis Data
	
For each year, the number of cases were aggregated, and were aggregated within each respective category. The diseases of interest were: Coronavirus Influenza (A & B), Parainfluenza, Respiratory Syncytial Virus (RSV), Metapneumovirus, and Rhinovirus. 
Instances of coronavirus and covid-19 were grouped together under the title of “coronavirus”, given covid is caused by a coronavirus. Influenza A & B were additionally grouped together under the title “Influenza”. 

Below is a sample of the cleaned data:

```{python}
#| label: disease-count-preview
#| fig-cap: "A line plot on a polar axis"

import polars as pl
import matplotlib.pyplot as plt
pl.Config.set_tbl_hide_column_data_types(True)  

raw_data = pl.read_csv("../data/02-analysis_data/disease_count.csv")
raw_data = raw_data.head(5)
raw_data
```
```{python}
#| label: yearly-count-preview
#| fig-cap: "A line plot on a polar axis"

import polars as pl
import matplotlib.pyplot as plt
pl.Config.set_tbl_hide_column_data_types(True)  


raw_data = pl.read_csv("../data/02-analysis_data/yearly_disease_count.csv")
raw_data = raw_data.head(5)
raw_data = raw_data.rename({"Coronavirus": "Corona", "Syncytial Virus": "RSV",
    "Metapneumovirus": "MPV",
    "Influenza": "Flu", "Rhinovirus": "RV", "Parainfluenza": "PIV"})
raw_data
```

Below are the summary statistics for the cleaned yearly count data:

```{python}
#| label: yearly-count-summary-statistics
#| fig-cap: "A line plot on a polar axis"

import polars as pl
import polars.selectors as sc
import matplotlib.pyplot as plt
pl.Config.set_tbl_hide_column_data_types(True)  
pl.Config(tbl_width_chars=5)

raw_data = pl.read_csv("../data/02-analysis_data/yearly_disease_count.csv")
summary_data = raw_data.describe()
summary_data = summary_data.filter(pl.col("statistic") != "count")
summary_data = summary_data.filter(pl.col("statistic") != "null_count")

summary_data = summary_data.rename({"Coronavirus": "Corona", "Syncytial Virus": "RSV",
    "Metapneumovirus": "MPV",
    "Influenza": "Flu", "Rhinovirus": "RV", "Parainfluenza": "PIV"})

summary_data = summary_data.with_columns(sc.by_dtype(pl.Float64).round(2))
summary_data.drop("Year")

```


# Results

## Overall Cases:
```{python}
#| label: all-graph
#| fig-cap: "A line plot on a polar axis"

import polars as pl
import matplotlib.pyplot as plt
import numpy as np

t = np.arange(2019, 2025, 1)
KEYS = ["Total", "Respiratory", "Coronavirus", "Influenza", "Syncytial Virus", "Metapneumovirus", "Rhinovirus", "Parainfluenza"]
df = pl.read_csv("../data/02-analysis_data/yearly_disease_count.csv")
raw_data = df.to_dict()
for key in KEYS:
  plt.plot(t, raw_data[key], marker = 'o', label = key)

plt.title("Outbreak Counts")
plt.xlabel("Year")
plt.ylabel("Outbreak Count")
plt.grid()

ax = plt.subplot(111)

# Shrink current axis by 20%
box = ax.get_position()
ax.set_position([box.x0, box.y0, box.width * 0.8, box.height])

# Put a legend to the right of the current axis
ax.legend(loc='center left', bbox_to_anchor=(1, 0.5))

plt.show()
```

We see that the total number of cases fluctuates with the number of respiratory cases, with number of outbreaks increasing since 2019 to 2022, and beginning to decrease afterwards.

The number of coronavirus cases also fluctuates with the number of respiratory cases and total cases, following the same trend described above.

## Makeup of Respiratory Outbreaks
```{python}
#| label: composition-chart
#| fig-cap: "Makeup of Respiratory Outbreaks from 2019-2024 inclusive"

### Workspace setup ####
import numpy as np
import polars as pl
import matplotlib.pyplot as plt

#### Read data ####
df = pl.read_csv("../data/02-analysis_data/disease_count.csv")
disease_comp = df.to_dict()

### Plot data ####
t = np.arange(2019, 2025, 1)

KEYS = ["Coronavirus", "Other", "Unknown"]

for key in KEYS:
  for i in range(6):
    disease_comp[key][i] = 100*disease_comp[key][i]/disease_comp["Total Agents"][i]

corona = np.array(disease_comp["Coronavirus"])
other = np.array(disease_comp["Other"])
unknown = np.array(disease_comp["Unknown"])

ind = np.arange(6)    
width = 0.35       

p1 = plt.bar(ind, corona, width, color='#d62728', )
p2 = plt.bar(ind, other, width,  bottom=corona)
p3 = plt.bar(ind, unknown, width,  bottom=corona+other)

plt.ylabel('Percentage of Causative Agents')
plt.title('Composition of Respiratory Disease Outbreaks')
plt.xticks(ind, ('2019', '2020', '2021', '2022', '2023', '2024'))
plt.yticks(np.arange(0, 110, 10))
plt.legend((p1[0], p2[0], p3[0]), ('Coronavirus', 'Other', "Unknown"))

plt.show()
```

It becomes evident that since the end of the pandemic, the proportion of Coronavirus outbreaks compared to non-coronavirus outbreaks has been steadily decreasing.

## Non-Covid Respiratory Outbreaks
```{python}
#| label: no-corona-graph
#| fig-cap: "A line plot on a polar axis"

import polars as pl
import matplotlib.pyplot as plt
import numpy as np

t = np.arange(2019, 2025, 1)
KEYS = ["Influenza", "Syncytial Virus", "Metapneumovirus", "Rhinovirus", "Parainfluenza"]
df = pl.read_csv("../data/02-analysis_data/yearly_disease_count.csv")
raw_data = df.to_dict()
for key in KEYS:
  plt.plot(t, raw_data[key], marker = 'o', label = key)

plt.title("Non-Coronavirus Respiratory Outbreaks")
plt.xlabel("Year")
plt.ylabel("Outbreak Count")
plt.grid()

ax = plt.subplot(111)

# Shrink current axis's height by 10% on the bottom
box = ax.get_position()
ax.set_position([box.x0, box.y0 + box.height * 0.1,
                 box.width, box.height * 0.9])

# Put a legend below current axis
ax.legend(loc='upper center', bbox_to_anchor=(0.5, -0.05),
          fancybox=True, shadow=True, ncol=5)

plt.show()
```

We see the number of Influenza (A & B), Parainfluenza, Respiratory Syncytial Virus (RSV), Metapneumovirus, and Rhinovirus outbreaks all generally fell to lower levels during the pandemic (2020-2021). 
Post pandemic (2022-2024), all, with the exception of Influenza, have resurged to greater than pre-pandemic (2019) levels. Influenza outbreaks have also increased since the pandemic, but remain at a lower level comparative to 2019.

# Discussion

It becomes apparent that given coronaviruses continue to comprise the greatest proportion of respiratory disease outbreaks in healthcare facilities in Toronto, and coronavirus outbreak trends match those of total respiratory outbreaks from, and total outbreaks from  2019-2024 that coronavirus outbreaks remain the biggest driver of disease outbreaks in Toronto. However, since the pandemic we have seen a decrease in both coronavirus cases, and percentage composition of all agents, indicating that its impact, while still pertinent, is decreasing. 

Simultaneously, other respiratory infections including Influenza, Parainfluenza, RSV, Metapneumovirus, and Rhinovirus have been experiencing a significant increase in outbreak cases. Though respiratory infections such as Influenza are well known to the public, those such as RSV are known to a much lesser extent with only 40% of adults having heard of RSV, and 30% who would definitely get the RSV vaccine. Compared to Influenza, this is a much lesser. (https://www.canada.ca/en/public-health/services/immunization-vaccines/vaccination-coverage/seasonal-influenza-survey-results-2023-2024.html). It is important to note that while these respiratory infections are less deadly than covid (https://www.nature.com/articles/s41598-024-55378-x ), many of these healthcare facilities are long term healthcare facilities, whose populations are more susceptible to these viruses.(https://www.cdc.gov/respiratory-viruses/risk-factors/older-adults.html#:~:text=As%20people%20get%20older%2C%20their,increasing%20sharply%20with%20advancing%20age. )

Altogether, this suggests a slightly greater emphasis should be placed on non-covid respiratory diseases, specifically RSV given it is the only one of the above which has a vaccine available which is not widely known, and outbreak numbers have risen in recent years post-pandemic. By campaigning for increased RSV vaccinations, when outbreaks do occur in healthcare facilities, they will be less deadly.


## Weaknesses and next steps

The main limitation of this study is the scale. All data is at the scale of healthcare facilities, thus must remain in the context of such. Extension of these results to the general Toronto population may be misrepresentative, thus to confirm the same trends hold in the general public further research should be conducted with data coming from the general population.

\newpage

\appendix



\newpage


# References


